# Generated by Django 2.2 on 2021-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=445)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('USers_who_liked_Quotes', models.ManyToManyField(related_name='Quotes_liked', to='BlackApp.User')),
                ('User_postingQuotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quotes_posted', to='BlackApp.User')),
            ],
        ),
    ]
